apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-demo
  namespace: app
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-demo
              image: batch-demo:v1
#              args:
#                - /bin/sh
#                - -c
#                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure

